---

- name: Configure ocsinventory
  block:
    - name: Setup ocsinventory log directory
      ansible.builtin.file:
        state: directory
        path: "{{ ocs_agent_logfile | dirname }}"
        mode: 0755
        owner: root
        group: root

    - name: Setup ocsinventory config directory
      ansible.builtin.file:
        state: directory
        path: "{{ ocs_agent_config_dir }}"
        mode: 0755
        owner: root
        group: root

    - name: Setup ocsinventory agent config file
      ansible.builtin.template:
        src: config.j2
        dest: "{{ ocs_agent_config_path }}"
        owner: root
        group: root
        mode: 0640

    - name: Setup ocsinventory agent sysconfig file
      ansible.builtin.template:
        src: sysconfig.j2
        dest: "{{ ocs_agent_syconfig_path }}"
        owner: root
        group: root
        mode: 0644

    - name: Configure ocsinventory logrotate
      ansible.builtin.template:
        src: logrotate.j2
        dest: "{{ ocs_agent_logrotate_path }}"
        owner: root
        group: root
        mode: 0644

    - name: Remove obsolete agent cron config
      ansible.builtin.file:
        path: "{{ ocs_agent_cron_file }}"
        state: absent
      loop: >-
        {{ ocs_agent_cron_alternatives
           | difference(["/etc/cron."
                          + ocs_agent_cron_frequency
                          + "/ocsinventory-agent" ]) }}
      loop_control:
        loop_var: ocs_agent_cron_file
      vars:
        ocs_agent_cron_alternatives:
          - /etc/cron.hourly/ocsinventory-agent
          - /etc/cron.daily/ocsinventory-agent
          - /etc/cron.weekly/ocsinventory-agent
          - /etc/cron.montly/ocsinventory-agent

    - name: Setup ocsinventory agent cron
      ansible.builtin.copy:
        dest: "/etc/cron.{{ ocs_agent_cron_frequency }}/ocsinventory-agent"
        content: |
          {{ "#!/bin/bash" }}

          {{ ocs_agent_exec_command }} > /dev/null 2>&1
        mode: 0755
      register: ocs_install_cron_create_result

    - name: Execute ocsinventory agent for the first time
      ansible.builtin.command: "{{ ocs_agent_exec_ansible.builtin.command }}"
      register: ocs_agent_exec_result
      failed_when: >-
        (ocs_agent_force_exec | bool)
           | ternary(false, ocs_agent_exec_result.rc != 0)
      when:
        - ocs_install_cron_create_result is changed
        - ocs_agent_exec_on_provision
  tags:
    - role::ocs_agent
    - role::ocs_agent::configure
