---
# Configure tasks

- block:
    - name: Setup ocsinventory agent config file
      template:
        src: config.j2
        dest: "{{ ocs_agent_config_path }}"

    - name: Setup ocsinventory agent sysconfig file
      template:
        src: sysconfig.j2
        dest: "{{ ocs_agent_syconfig_path }}"

    - name: Configure ocsinventory logrotate
      template:
        src: logrotate.j2
        dest: "{{ ocs_agent_logrotate_path }}"

    - name: Remove obsolete agent cron config
      file:
        path: "{{ ocs_agent_cron_file }}"
        state: absent
      loop: >-
        {{ ocs_agent_cron_alternatives
           | difference(["/etc/cron."
                          + ocs_agent_cron_frequency
                          + "/ocsinventory-agent" ]) }}
      loop_control:
        loop_var: ocs_agent_cron_file
      vars:
        ocs_agent_cron_alternatives:
          - /etc/cron.hourly/ocsinventory-agent
          - /etc/cron.daily/ocsinventory-agent
          - /etc/cron.weekly/ocsinventory-agent
          - /etc/cron.montly/ocsinventory-agent

    - name: Setup ocsinventory agent cron
      copy:
        src: "{{ ocs_agent_config_dir }}/cron"
        dest: "/etc/cron.{{ ocs_agent_cron_frequency }}/ocsinventory-agent"
        remote_src: yes
        mode: 0755
  tags:
    - role::ocs_agent
    - role::ocs_agent::configure
