---
# Configure tasks

- block:
    - name: Setup ocsinventory agent config file
      template:
        src: config.j2
        dest: "{{ ocs_agent_config_path }}"

    - name: Setup ocsinventory agent sysconfig file
      template:
        src: sysconfig.j2
        dest: "{{ ocs_agent_syconfig_path }}"

    - name: Configure ocsinventory logrotate
      template:
        src: logrotate.j2
        dest: "{{ ocs_agent_logrotate_path }}"

    - name: Check default cron file
      stat:
        path: "{{ ocs_agent_cron_default_path }}"
      register: ocs_agent_check_cron_result
      when:
        - ocs_agent_mode is defined
        - ocs_agent_mode == "cron"

    - name: Remove ocsinventory agent default cron
      command: >-
        mv {{ ocs_agent_cron_default_path }}
        {{ ocs_agent_config_dir }}/cron
      when:
        - ocs_agent_mode is defined
        - ocs_agent_mode == 'cron'
        - ocs_agent_check_cron_result.stat.exists

    - name: Remove obsolete agent cron config
      file:
        path:
        state: absent
      loop: >-
        {{ ocs_agent_cron_alternatives
           | difference(["/etc/cron."
                          + ocs_agent_cron_frequency
                          + "/ocsinventory-agent" ]) }}
      vars:
        ocs_agent_cron_alternatives:
          - /etc/cron.hourly/ocsinventory-agent
          - /etc/cron.daily/ocsinventory-agent
          - /etc/cron.weekly/ocsinventory-agent
          - /etc/cron.montly/ocsinventory-agent

    - name: Setup ocsinventory agent cron
      copy:
        src: "{{ ocs_agent_config_dir }}/cron"
        dest: "/etc/cron.{{ ocs_agent_cron_frequency }}"
        remote_src: yes
        mode: 0755
      when:
        - ocs_agent_mode is defined
        - ocs_agent_mode == 'cron'
  tags:
    - role::ocs_agent
    - role::ocs_agent::configure
