---
# install tasks

- block:
    # - name: Check ocsinventory repository
    #   stat:
    #     path: /etc/yum.repos.d/ocsinventory.repo
    #   register: ocs_agent_repo_check_result

    # - name: Download ocsinventory repository rpm
    #   include_role:
    #     name: amtega.artifact
    #   vars:
    #     artifact_list:
    #       - "{{ ocs_agent_artifact }}"
    #   when: not ocs_agent_repo_check_result.stat.exists
    #
    # - name: Setup ocsinventory repository
    #   package:
    #     name: "{{ artifact_result.ocsinventory_repo.download_path }}"
    #     state: present
    #   when: not ocs_agent_repo_check_result.stat.exists
    #


    - name: Check ocsinventory
      command: ocsinventory-agent --version
      register: ocs_agent_check_result
      failed_when: no
      changed_when: no

    - block:
        - name: Download ocsinventory artifacts
          include_role:
            name: amtega.artifact
          vars:
            artifact_overrides:
              id: ocsinventory_agent
              unarchive: yes
            artifact_overriden: >-
              {{ ocs_agent_artifact | combine(artifact_overrides) }}
            artifact_list: "{{ [ artifact_overriden ] }}"

        - name: Prepare ocsinventory agent build
          shell: PERL_AUTOINSTALL=1 perl Makefile.PL
          args:
            chdir: /tmp/Ocsinventory-Unix-Agent-2.4.2
            warn: no

        - name: Build ocsinventory build
          command: make
          args:
            chdir: /tmp/Ocsinventory-Unix-Agent-2.4.2

        - name: Install ocsinventory
          command: make install
          args:
            chdir: /tmp/Ocsinventory-Unix-Agent-2.4.2

    #
    #     - name: Install ocsinventory agent packages
    #       package:
    #         name: "{{ lookup('template', 'packages.j2') | from_yaml }}"
    #         state: present
      when: >-
        not ocs_agent_check_result.stdout | default("")
        is search("Ocsinventory unified agent for UNIX")
  tags:
    - role::ocs_agent
    - role::ocs_agent::install
