---
# Install tasks

- block:
    - name: Install needed software
      include_role:
        name: amtega.packages
      vars:
        packages_os: "{{ ocs_agent_packages_os }}"
        
    - block:
        - name: Search powertools repo config file
          find:
            paths: /etc/yum.repos.d
            file_type: file
            patterns: "*.repo"
            contains: ".*\\[powertools\\].*"
          register: ocs_agent_search_powertools_result

        - name: Enable powertools
          community.general.ini_file:
            path: >-
              {{ ocs_agent_search_powertools_result.files.0.path }}
            section: powertools
            option: enabled
            value: "1"
            mode: "0644"

        - name: Yum update cache
          ansible.builtin.yum:
            update_cache: yes
      when:
        - ansible_facts.distribution_major_version is version("8", ">=")
        - ansible_facts.distribution | lower != "fedora"

    - name: install ocs agent
      package:
        name: "ocsinventory-agent"
        state: present
      register: ocs_agent_install_result

  tags:
    - role::ocs_agent
    - role::ocs_agent::install
