---
# install tasks

- block:
    - name: Check ocsinventory
      command: ocsinventory-agent --version
      register: ocs_agent_check_result
      failed_when: no
      changed_when: no

    - name: Get ocsinventory agent releases info from official site
      uri:
        url: "{{ ocs_agent_repo_host + ocs_agent_repo_releases }}"
        return_content: yes
      register: ocs_agent_get_releases_result
      when:
        - ocs_agent_version is not defined
        - ocs_agent_artifact is not defined

    - block:
        - name: Download ocsinventory artifacts
          include_role:
            name: amtega.artifact
          vars:
            artifact_list:
              - "{{ ocs_agent_artifact_overriden }}"

        - name: Prepare ocsinventory agent build
          shell: perl Makefile.PL INSTALLDIRS=vendor
          args:
            chdir: "{{ ocs_agent_build_dir }}"
            warn: no

        - name: Build ocsinventory build
          command: make
          args:
            chdir: "{{ ocs_agent_build_dir }}"

        - name: Install ocsinventory
          command: make pure_install
          args:
            chdir: "{{ ocs_agent_build_dir }}"

        - name: Install ocsinventory agent config directory
          synchronize:
            src: "{{ ocs_agent_build_dir }}/etc/ocsinventory-agent"
            dest: "{{ ocs_agent_config_dir }}"
          delegate_to: "{{ inventory_hostname }}"

        - name: Install ocsinventory template cron file
          copy:
            src: "{{ ocs_agent_build_dir }}/etc/cron.d/ocsinventory-agent"
            dest: "{{ ocs_agent_config_dir }}/cron"
            remote_src: yes
      when: ocs_agent_installed_version != ocs_agent_version_to_install
      vars:
        ocs_agent_installed_version: >-
          {{ ocs_agent_check_result.stdout
             | default("")
             | regex_replace(".*\((.*)\)", "\1") }}
        ocs_agent_build_dir: >-
          /tmp/Ocsinventory-Unix-Agent-{{ ocs_agent_version_to_install }}
  tags:
    - role::ocs_agent
    - role::ocs_agent::install
