---

- name: Install ocsinventory
  block:
    - name: Install ocsinventory from powertools
      block:
        - name: Search powertools/codeready-builder repo config file
          ansible.builtin.find:
            paths: /etc/yum.repos.d
            file_type: file
            patterns: "*.repo"
            contains: ".*\\[{{ ocs_agent_ptcrb_repo_section }}\\].*"
          register: ocs_agent_search_ptcrb_result

        - name: Enable powertools/codeready-builder repo
          community.general.ini_file:
            path: >-
              {{ ocs_agent_search_ptcrb_result.files.0.path }}
            section: "{{ ocs_agent_ptcrb_repo_section }}"
            option: enabled
            value: "1"
            no_extra_spaces: yes
            mode: "0644"

        - name: Update package manager cache
          ansible.builtin.yum:
            update_cache: yes
      when:
        - ansible_facts.distribution_major_version is version("8", ">=")
        - ansible_facts.distribution | lower != "fedora"
      vars:
        ocs_agent_ptcrb_repo_section: >-
          {{ (ansible_facts.distribution | lower == "redhat")
             | ternary("codeready-builder-for-rhel-8-"
                       + ansible_facts.architecture
                       + "-rpms",
                       "powertools") }}

    - name: Setup packages
      ansible.builtin.include_role:
        name: amtega.packages
      vars:
        packages_os: "{{ ocs_agent_packages_os }}"

    - name: Manage ipmi dependency
      ansible.builtin.package:
        name: ipmitool
        state: "{{ ocs_agent_ipmitool_dependency }}"
  tags:
    - role::ocs_agent
    - role::ocs_agent::install
