---
# Role tasks

- name: Gather ocsinventory facts
  include_tasks: facts.yml
  tags:
    - role::ocs_agent
    - role::ocs_agent::facts

- block:
    - name: Install ocsinventory agent
      include_tasks: install.yml
      when: ocs_agent_installed_version != ocs_agent_version_to_install
  environment: "{{ proxy_client_environment }}"
  tags:
    - role::ocs_agent
    - role::ocs_agent::install

- name: Configure ocsinventory agent
  include_tasks: configure.yml
  tags:
    - role::ocs_agent
    - role::ocs_agent::configure
