---
# Role tasks

- name: Install ocsinventory agent
  include_tasks: install.yml
  tags:
    - role::ocs_agent
    - role::ocs_agent::install

- name: Configure ocsinventory agent
  include_tasks: configure.yml
  tags:
    - role::ocs_agent
    - role::ocs_agent::configure
