---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: molecule_hosts
  tasks:
    - name: Check ocsinventory agent install
      ansible.builtin.command: ocsinventory-agent --version
      register: ocs_agent_check
      changed_when: no
      failed_when: >-
        not ocs_agent_check.stdout
        is search("Ocsinventory unified agent for UNIX")

    - name: Check cron file location is correct (Asume role defaults)
      ansible.builtin.stat:
        path: "/etc/cron.daily/ocsinventory-agent"
      register: ocs_agent_cron_check
      changed_when: no

    - name: Check logrotate file location is correct (Asume role defaults)
      ansible.builtin.stat:
        path: /etc/logrotate.d/ocsinventory-agent
      register: ocs_agent_logrotate_check
      changed_when: no

    - name: Check install
      ansible.builtin.assert:
        that:
          - ocs_agent_cron_check.stat.exists
          - ocs_agent_logrotate_check.stat.exists
