---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Check ocsinventory agent install
    command: ocsinventory-agent --version
    register: ocs_agent_check
    changed_when: no
    failed_when: >-
      not ocs_agent_check.stdout
      is search("Ocsinventory unified agent for UNIX")

  - name: Check cron file location is correct
    stat:
      path: "/etc/cron.{{ ocs_agent_cron_frequency }}/ocsinventory-agent"
    register: ocs_agent_cron_check
    changed_when: no

  - name: Check logrotate file location is correct
    stat:
      path: "{{ ocs_agent_logrotate_path }}"
    register: ocs_agent_logrotate_check
    changed_when: no

  - name: Check install
    assert:
      that:
        - ocs_agent_cron_check.stat.exists
        - ocs_agent_logrotate_check.stat.exists
